### ISSUE TITLE
Error in rstudio::conf 2020 slides

### ISSUE THREAD

**Issue by dantonnoriega** [TysonStanley/tysonstanley.github.io#1]
The code in the slides (maybe starting on slide 16) I think is incorrect.

```
sw <- as.data.table(dplyr::starwars)
sw <- sw[, .(films = films[[1]]), by = c(...))
```

First, just a typo: no closing `]`. Second, `films[[1]]` doesn't generate the correct behavior (at least not for me). Instead, `unlist(films)` seems more appropriate.

```
sw <- as.data.table(dplyr::starwars)
sw <- sw[, .(films = unlist(films)), by = c(...)]
```

I also can't seem to  unnest the counts later one. Anyhow, heres a reprex of what I found works and doesn't work.

```r
sw <- data.table::as.data.table(dplyr::starwars)

sw[, .(films = films[[1]]), by = c('name', 'species')] # fails
sw[, .(films = unlist(films)), by = c('name', 'species')] # works

sw <- sw[, .(films = unlist(films)), by = c('name', 'species')]
swn <- sw[, .(data = list(.SD)), by = films]

# tibble style
swn[, counts := purrr::map(data, ~dplyr::count(.x, species))] # tibble
swn[, counts[[1]], by = films] # fails
swn[, rbindlist(counts), by = films] # works

# data.table style
swn[, counts := lapply(data, '[', j = .N, by = 'species')]
swn[, counts[[1]], by = films] # fails
swn[, rbindlist(counts), by = films] # works
```

Could totally be my version of `R` or of `data.table`, so heres my session info:

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8 magrittr_1.5      colorout_1.2-0   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3       fansi_0.4.0      utf8_1.1.4       zeallot_0.1.0    packrat_0.5.0    crayon_1.3.4    
 [7] dplyr_0.8.3      assertthat_0.2.1 R6_2.4.1         backports_1.1.5  pillar_1.4.2     rlang_0.4.2     
[13] rstudioapi_0.10  vctrs_0.2.0      tools_3.5.3      glue_1.3.1       purrr_0.3.2      compiler_3.5.3  
[19] pkgconfig_2.0.3  tidyselect_0.2.5 tibble_2.1.3   
```

**Comment by TysonStanley** [comment]
@dantonnoriega Thanks for catching that error. You are right that I missed a `]` in those early slides. I've updated the slides to be the correct version.

In the slides (and in the recording that isn't up yet...) I also mention that these approaches only work with the developmental version (because in that version they fix a weird bug that keeps the presented approaches from working right). Using `unlist()` and `rbindlist()` like you did is exactly how [`tidyfast`](https://github.com/TysonStanley/tidyfast) is currently implemented because it works with all versions of `data.table`. It is super fast and not too difficult to implement. However, for the presentation I wanted to present the newest and best approach to it so I relied on the developmental version.
